/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.tut.pizzaorderingsystem;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import za.ac.tut.pizzadatainterface.PizzaDataInterface;

/**
 *
 * @author acer
 */
public class PizzaOrderingApp extends javax.swing.JFrame implements MouseListener,PizzaDataInterface {

    String size;
    String name;
    double price ;
     int priceInitial;
    /**
     * Creates new form PizzaOrderingApp
     */
    public PizzaOrderingApp() {
        initComponents();
       
        
        mincedMeat.addMouseListener(this);
        peperonni.addMouseListener(this);
        cremeBrule.addMouseListener(this);
        piccoloHeart.addMouseListener(this);
        veggies.addMouseListener(this);
         coke.addMouseListener(this);
          watermelon.addMouseListener(this);
          mixedFruit.addMouseListener(this);
           orange.addMouseListener(this);
        
        
    }

     DefaultTableModel model=new  DefaultTableModel();
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTxt = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        mincedMeat = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        piccoloHeart = new javax.swing.JLabel();
        veggies = new javax.swing.JLabel();
        peperonni = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cremeBrule = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        coke = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        mixedFruit = new javax.swing.JLabel();
        orange = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        watermelon = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtbal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        paytxt = new javax.swing.JTextField();
        smallButton = new javax.swing.JRadioButton();
        mediumButton = new javax.swing.JRadioButton();
        largeButton = new javax.swing.JRadioButton();
        extraLargeButton = new javax.swing.JRadioButton();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        printButton = new javax.swing.JButton();
        jScrollBar2 = new javax.swing.JScrollBar();
        addFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));
        jPanel1.setForeground(new java.awt.Color(51, 255, 255));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("BLISS  PIZZA APP");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/za/ac/tut/pizzaorderingsystem/logo_pizza_small.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(1093, 1093, 1093))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        tableTxt.setBackground(new java.awt.Color(51, 51, 51));
        tableTxt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "size", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTxt);

        jTabbedPane2.setName("Pizza"); // NOI18N

        mincedMeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/za/ac/tut/pizzaorderingsystem/mince_meat_small.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mincedMeat)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(mincedMeat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        piccoloHeart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/za/ac/tut/pizzaorderingsystem/piccolo_heart_small.jpg"))); // NOI18N

        veggies.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\vegies_Pizza_small.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(piccoloHeart)
                .addGap(27, 27, 27)
                .addComponent(veggies, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(veggies)
                            .addComponent(piccoloHeart))))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        peperonni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/za/ac/tut/pizzaorderingsystem/peperonni_small.jpg"))); // NOI18N
        peperonni.setText("jLabel5");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );

        cremeBrule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/za/ac/tut/pizzaorderingsystem/creme_brule_updated.jpg"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("CHOOSE YOUR FLAVOUR:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(peperonni, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(cremeBrule))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1319, 1319, 1319)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(cremeBrule))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(peperonni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("PIZZA", jPanel8);

        coke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/za/ac/tut/pizzaorderingsystem/ice_coke.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coke, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(coke)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        mixedFruit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/za/ac/tut/pizzaorderingsystem/mixed_fruit.png"))); // NOI18N

        orange.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\juice_mango.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mixedFruit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orange))
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(76, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orange, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mixedFruit, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(310, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        watermelon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/za/ac/tut/pizzaorderingsystem/watermelon_juice.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(watermelon, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(watermelon)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("DRINKS ", jPanel9);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel14.setText("TOTAL");

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("BALANCE");

        txtbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("PAYMENT");

        paytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paytxtActionPerformed(evt);
            }
        });

        smallButton.setText("Small");
        smallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallButtonActionPerformed(evt);
            }
        });

        mediumButton.setText("Medium");

        largeButton.setText("Large");

        extraLargeButton.setText("ExtraLarge");
        extraLargeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraLargeButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("CHOOSE THE SIZE:");

        txtBill.setColumns(20);
        txtBill.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtBill.setRows(5);
        jScrollPane2.setViewportView(txtBill);

        printButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printButton.setText("PRINT INVOICE");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        addFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addFile.setText("ADD INTO FILE");
        addFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1431, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(paytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(addFile)))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(printButton)
                                        .addGap(81, 81, 81))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtbal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(largeButton)
                                    .addComponent(extraLargeButton)
                                    .addComponent(mediumButton)
                                    .addComponent(smallButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(28, 28, 28)
                                .addComponent(smallButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mediumButton)
                                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(largeButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(extraLargeButton))
                                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(addFile, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void paytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paytxtActionPerformed

    
    
    private void txtbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbalActionPerformed

    private void smallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       
        // COMPONENTS OF THE ADD BUTTON 
     
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
       
        model.removeRow(tableTxt.getSelectedRow());
         int sum =0;  
      for (int i=0;i<tableTxt.getRowCount();i++){
          sum=(int) (sum +Double.parseDouble(tableTxt.getValueAt(i,3).toString()));
            
        txttotal.setText(Integer.toString(sum));
      }
    }//GEN-LAST:event_removeButtonActionPerformed

      public void balance(){
        
        double tot=Integer.parseInt(txttotal.getText());
        double pay =Integer.parseInt(paytxt.getText());
        
        double balance=pay-tot;
        txtbal.setText(String.valueOf(balance));
        
        if(tot<pay){
            
             JOptionPane.showMessageDialog(null, "Sales completeeeeedddddddd","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        
    }
      
      public void billPrinting(){
          
          String tot= txttotal.getText();
          String pay =paytxt.getText() ;
          String balance =txtbal.getText() ;
          
           DefaultTableModel model=new  DefaultTableModel();
           model =(DefaultTableModel)tableTxt.getModel();
           
          txtBill.setText(txtBill.getText()+"******************************************************************\n");
           txtBill.setText(txtBill.getText()+"            BLISS PIZZA BILL                                      \n");
          txtBill.setText(txtBill.getText()+"*******************************************************************\n");
          
              //HEADING
          
          txtBill.setText(txtBill.getText()+" Items "+"\t"+" Price "+"\t"+" Amount"+"\n");
          //iteratethrough
          for(int i=0;i<model.getRowCount();i++){
             String name =(String)model.getValueAt(i,0);
             String size =(String)model.getValueAt(i,1);
              String price=(String)model.getValueAt(i,2);
               
               txtBill.setText(txtBill.getText()+name+"\t"+size+"\t"+price+"\n");
              
          }
          txtBill.setText(txtBill.getText()+"\n");
        
           txtBill.setText(txtBill.getText()+"\t"+"\t"+"SubTotal:"+tot);
           txtBill.setText(txtBill.getText()+"\t"+"\t"+"Payment:"+pay);
           txtBill.setText(txtBill.getText()+"\t"+"\t"+"ChangeAmount:"+balance);
             txtBill.setText(txtBill.getText()+"\n");
          
          txtBill.setText(txtBill.getText()+"******************************************************************\n");
          txtBill.setText(txtBill.getText()+"            THANK YOU,COME AGAIN !!!!!                             \n");
          
      }
    
    
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // declare the method to display tghe balance
            balance();
       billPrinting();
    
    }//GEN-LAST:event_printButtonActionPerformed

    private void extraLargeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraLargeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extraLargeButtonActionPerformed

    private void addFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileActionPerformed
        // add into a file 
        
        
          String tot= txttotal.getText().toString();
          String pay =paytxt.getText().toString() ;
          String balance =txtbal.getText().toString() ;
          
        try{
            FileWriter writer=new FileWriter("/.file.txt",true);
            writer.write(tot+",");
            writer.write(System.getProperty("line.separator"));
            writer.write(pay+",");
             writer.write(System.getProperty("line.separator"));
            writer.write(balance+",");
            
            JOptionPane.showMessageDialog(rootPane,"Success");
            
            
            
            
        }catch (Exception e){
            
            JOptionPane.showMessageDialog(rootPane,"Error");
        }
        
        
        
        
    }//GEN-LAST:event_addFileActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaOrderingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaOrderingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaOrderingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaOrderingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaOrderingApp().setVisible(true);
            }
        });

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addFile;
    private javax.swing.JLabel coke;
    private javax.swing.JLabel cremeBrule;
    private javax.swing.JRadioButton extraLargeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton largeButton;
    private javax.swing.JRadioButton mediumButton;
    private javax.swing.JLabel mincedMeat;
    private javax.swing.JLabel mixedFruit;
    private javax.swing.JLabel orange;
    private javax.swing.JTextField paytxt;
    private javax.swing.JLabel peperonni;
    private javax.swing.JLabel piccoloHeart;
    private javax.swing.JButton printButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JRadioButton smallButton;
    private javax.swing.JTable tableTxt;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextField txttotal;
    private javax.swing.JLabel veggies;
    private javax.swing.JLabel watermelon;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        //First pizza
      if(e.getSource()==mincedMeat && smallButton.isSelected() ==true){          
           name ="minced Meat";  
           size = "Small";
           price=PizzaDataInterface.PRICE_MINCED_MEAT_SMALL;
           
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price*qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==mincedMeat && mediumButton.isSelected() ==true){          
           name ="Minced Meat";  
           size = "Medium";
           price= PizzaDataInterface.PRICE_MINCED_MEAT_MEDIUM;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==mincedMeat && largeButton.isSelected() ==true){          
           name ="Minced Meat";  
           size = "Large";
           price= PizzaDataInterface.PRICE_MINCED_MEAT_LARGE;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==mincedMeat && extraLargeButton.isSelected() ==true){          
           name ="Minced Meat";  
           size = "Extra large";
           price= 299;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }    
      else if(e.getSource()==peperonni && smallButton.isSelected() ==true){          
           name ="Peperonni";  
           size = "Small";
           price= PizzaDataInterface.PRICE_PEPPERONI_SMALL;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
     else if(e.getSource()==peperonni && mediumButton.isSelected() ==true){          
           name ="Peperonni";  
           size = "Medium";
           price= PizzaDataInterface.PRICE_PEPPERONI_MEDIUM;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
    else  if(e.getSource()==peperonni && largeButton.isSelected() ==true){          
           name ="Peperonni";  
           size = "Large";
           price= PizzaDataInterface.PRICE_PEPPERONI_LARGE;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
     else if(e.getSource()==peperonni && extraLargeButton.isSelected() ==true){          
           name ="Peperonni";  
           size = "Extra large";
           price= 289;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==peperonni && smallButton.isSelected() ==true){          
           name ="Peperonni";  
           size = "Small";
           price= PizzaDataInterface.PRICE_PEPPERONI_SMALL;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
     else if(e.getSource()==peperonni && mediumButton.isSelected() ==true){          
           name ="Peperonni";  
           size = "Medium";
           price= PizzaDataInterface.PRICE_PEPPERONI_MEDIUM;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
    else  if(e.getSource()==peperonni && largeButton.isSelected() ==true){          
           name ="Peperonni";  
           size = "Large";
           price= PizzaDataInterface.PRICE_PEPPERONI_LARGE;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double  tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
     else if(e.getSource()==peperonni && extraLargeButton.isSelected() ==true){          
           name ="Peperonni";  
           size = "Extra large";
           price= 289;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      //THE THIRD PIZZA 
     else if(e.getSource()==piccoloHeart && smallButton.isSelected() ==true){          
           name ="Piccolo Heart";  
           size = "Small";
           price= PizzaDataInterface.PRICE_PICCOLO_HEART_SMALL;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==piccoloHeart && mediumButton.isSelected() ==true){          
           name ="Piccolo Heart";  
           size = "Medium";
           price= PizzaDataInterface.PRICE_PICCOLO_HEART_MEDIUM;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==piccoloHeart && largeButton.isSelected() ==true){          
           name ="Piccolo Heart";  
           size = "Large";
           price= PizzaDataInterface.PRICE_PICCOLO_HEART_LARGE;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==piccoloHeart && extraLargeButton.isSelected() ==true){          
           name ="Piccolo Heart";  
           size = "Extra large";
           price= 299;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      //FOURTH PIZZA
      if(e.getSource()==veggies && smallButton.isSelected() ==true){          
           name ="Veggies";  
           size = "Small";
           price= PizzaDataInterface.PRICE_VEGGIES_SMALL;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==veggies && mediumButton.isSelected() ==true){          
           name ="Veggies";  
           size = "Medium";
           price= PizzaDataInterface.PRICE_VEGGIES_MEDIUM;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==veggies && largeButton.isSelected() ==true){          
           name ="Veggies";  
           size = "Large";
           price= PizzaDataInterface.PRICE_VEGGIES_LARGE;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }
      else if(e.getSource()==veggies && extraLargeButton.isSelected() ==true){          
           name ="Veggies";  
           size = "Extra large";
           price= 299;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
        double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });
      }else if(e.getSource()==coke && smallButton.isSelected() ==true){
          
         name ="Coke";  
         size = "Small";
           price= PizzaDataInterface.PRICE_COKE_SMALL;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
         
          
      }else if(e.getSource()==coke && mediumButton.isSelected() ==true){
          
         name ="Coke";  
           size = "Medium";
           price= PizzaDataInterface.PRICE_COKE_MEDIUM;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
         
      }else if(e.getSource()==coke && largeButton.isSelected() ==true){
          
           name ="Coke";  
           size = "Large";
           price= PizzaDataInterface.PRICE_COKE_LARGE;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
      
      //second Dink 
      }else if(e.getSource()==watermelon && smallButton.isSelected() ==true){
          
         name ="Watermelon";  
           size = "Small";
           price= PizzaDataInterface.PRICE_WATERMELON_SMALL;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });   
      }else if(e.getSource()==watermelon && mediumButton.isSelected() ==true){
          
         name ="Watermelon";  
           size = "Medium";
           price= PizzaDataInterface.PRICE_WATERMELON_MEDIUM;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
         
      }else if(e.getSource()==watermelon && largeButton.isSelected() ==true){
          
           name ="Watermelon";  
           size = "Large";
           price= PizzaDataInterface.PRICE_WATERMELON_LARGE;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
        double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
        
      //THIRD DRINK
      }else if(e.getSource()==mixedFruit && smallButton.isSelected() ==true){
          
         name ="MixedFruit";  
           size = "Small";
           price= PizzaDataInterface.PRICE_MIXED_FRUIT_SMALL;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
      }else if(e.getSource()==mixedFruit && mediumButton.isSelected() ==true){
          
         name ="MixedFruit";  
           size = "Medium";
           price= PizzaDataInterface.PRICE_MIXED_FRUIT_MEDIUM;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
         
      }else if(e.getSource()==mixedFruit && largeButton.isSelected() ==true){
          
           name ="MixedFruit";  
           size = "Large";
           price=  PizzaDataInterface.PRICE_MIXED_FRUIT_LARGE;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
      
        //Fourth drink 
      }else if(e.getSource()==orange&& smallButton.isSelected() ==true){
          
         name ="Orange";  
           size = "Small";
           price= PizzaDataInterface.PRICE_ORANGE_JUICE_SMALL;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        });  
          
      }else if(e.getSource()==mixedFruit && mediumButton.isSelected() ==true){
          
         name ="Orange";  
           size = "Medium";
           price= PizzaDataInterface.PRICE_ORANGE_JUICE_MEDIUM;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
         
      }else if(e.getSource()==mixedFruit && largeButton.isSelected() ==true){
          
           name ="Orange";  
           size = "Large";
           price= PizzaDataInterface.PRICE_ORANGE_JUICE_LARGE;          
          //Enter the quantity
          int qty=Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity: "));
          //determine the sum 
         double tot =(price *qty);
        model =(DefaultTableModel)tableTxt.getModel();
        model.addRow(new Object[]{            
        name,size,price,qty,tot  
        }); 
      } 
      //sum up the content int the table 
      int sum =0;
      for(int s =0;s<tableTxt.getRowCount();s++){
          sum=(int) (Double.parseDouble(tableTxt.getValueAt(s, 4).toString())+sum);
          txttotal.setText(Integer.toString(sum));  
      }
    }
    
    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
